<?php
/**
 * Auto generated by prado-cli.php on 2009-02-06 12:06:23.
 * Para el uso de activeRecords en el momento de la autenticacion de usuarios
 */
class personas extends TActiveRecord
{
	const TABLE='organizacion.personas';

	public $id;
	public $cedula;
	public $carnet;
	public $nombres;
	public $apellidos;
	public $fecha_nacimiento;
	public $lugar_nacimiento;
	public $sexo;
	public $edo_civil;
	public $profesion;
	public $grado_instruccion;
	public $fecha_ingreso;
	public $direccion;
	public $tlf_habitacion;
	public $tlf_celular;
	public $foto;

	public $datos_usuario;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public static $RELATIONS=array
	(
		'cedula'=> array(self::BELONGS_TO, 'usuarios'),
	);

}
?>
