<?php
/**
 * Auto generated by prado-cli.php on 2009-02-06 12:03:09.
 * Para el uso de activeRecords en el momento de la autenticacion de usuarios
 */
class usuarios extends TActiveRecord
{
	const TABLE='intranet.usuarios';

	public $id;
	public $cedula;
	public $login;
	public $clave;
	public $email;
	public $activo;
	public $datos_personales;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public static $RELATIONS=array
	(
		'cedula'=> array(self::BELONGS_TO, 'personas'),
	);

}
?>
